### ISSUE TITLE
Application crashes if open for too long

### ISSUE THREAD

**Issue by unstephenk** [ushahidi/platform-android#11]
I left the application open about 8 minutes and the app crashes. Logcat error: 

    04-25 16:25:52.067  21388-21388/com.ushahidi.android E/art﹕ Throwing OutOfMemoryError "Failed
    to allocate a 34155880 byte allocation with 16777216 free bytes and 27MB until OOM"
    04-25 16:25:52.067  21388-21388/com.ushahidi.android E/AndroidRuntime﹕ Error reporting crash
    java.lang.OutOfMemoryError: Failed to allocate a 34155880 byte allocation with 16777216 free
    bytes and 27MB until OOM
            at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
            at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:125)
            at java.lang.StringBuffer.append(StringBuffer.java:278)

**Comment by eyedol** [comment]
I suspect memory leaks. Should be addressed in the `develop` branch
