### ISSUE TITLE
Sort by Title Crashes App

### ISSUE THREAD

**Issue by eyedol** [ushahidi/platform-android#75]
Here is the stacktrace.

```E/MessageQueue-JNI( 5618): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareTo(java.lang.String)' on a null object reference
    E/MessageQueue-JNI( 5618): at com.ushahidi.android.presentation.view.ui.adapter.PostAdapter.lambda$sortByTitle$63(PostAdapter.java:152)
    E/MessageQueue-JNI( 5618): at com.ushahidi.android.presentation.view.ui.adapter.PostAdapter.access$lambda$1(PostAdapter.java)
    E/MessageQueue-JNI( 5618): at com.ushahidi.android.presentation.view.ui.adapter.PostAdapter$$Lambda$2.compare(Unknown Source)
    E/MessageQueue-JNI( 5618): at java.util.TimSort.binarySort(TimSort.java:261)
    E/MessageQueue-JNI( 5618): at java.util.TimSort.sort(TimSort.java:204)
    E/MessageQueue-JNI( 5618): at java.util.TimSort.sort(TimSort.java:169)
    E/MessageQueue-JNI( 5618): at java.util.Arrays.sort(Arrays.java:2010)
    E/MessageQueue-JNI( 5618): at java.util.Collections.sort(Collections.java:1883)
    E/MessageQueue-JNI( 5618): at com.ushahidi.android.presentation.view.ui.adapter.PostAdapter.sortByTitle(PostAdapter.java:152)
    E/MessageQueue-JNI( 5618): at com.ushahidi.android.presentation.view.ui.fragment.ListPostFragment.sortByTitle(ListPostFragment.java:221)
    E/MessageQueue-JNI( 5618): at com.ushahidi.android.presentation.view.ui.fragment.ListPostFragment.onOptionsItemSelected(ListPostFragment.java:204)
    E/MessageQueue-JNI( 5618): at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2070)
    E/MessageQueue-JNI( 5618): at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2108)
    E/MessageQueue-JNI( 5618): at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:295)
    E/MessageQueue-JNI( 5618): at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:331)
    E/MessageQueue-JNI( 5618): at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
    E/MessageQueue-JNI( 5618): at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
    E/MessageQueue-JNI( 5618): at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
    E/MessageQueue-JNI( 5618): at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:73)
    E/MessageQueue-JNI( 5618): at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
    E/MessageQueue-JNI( 5618): at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
    E/MessageQueue-JNI( 5618): at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
    E/MessageQueue-JNI( 5618): at android.support.v7.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:84)
    E/MessageQueue-JNI( 5618): at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    E/MessageQueue-JNI( 5618): at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
    E/MessageQueue-JNI( 5618): at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
    E/MessageQueue-JNI( 5618): at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:191)
    E/MessageQueue-JNI( 5618): at android.widget.AdapterView.performItemClick(AdapterView.java:305)
    E/MessageQueue-JNI( 5618): at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
    E/MessageQueue-JNI( 5618): at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
    E/MessageQueue-JNI( 5618): at android.widget.AbsListView.onTouchUp(AbsListView.java:3872)
    E/MessageQueue-JNI( 5618): at android.widget.AbsListView.onTouchEvent(AbsListView.java:3637)
    E/MessageQueue-JNI( 5618): at android.view.View.dispatchTouchEvent(View.java:8471)
    E/MessageQueue-JNI( 5618): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
    E/MessageQueue-JNI( 5618): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
    E/MessageQueue-JNI( 5618): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
    E/MessageQueue-JNI( 5618): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
    E/MessageQueue-JNI( 5618): at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1731)
    E/MessageQueue-JNI( 5618): at android.view.View.dispatchPointerEvent(View.java:8666)
    E/MessageQueue-JNI( 5618): at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
    E/MessageQueue-JNI( 5618): at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
    E/MessageQueue-JNI( 5618): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
    E/MessageQueue-JNI( 5618): at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
    E/MessageQueue-JNI( 5618): at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
    E/MessageQueue-JNI( 5618): at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
    E/MessageQueue-JNI( 5618): at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
    E/MessageQueue-JNI( 5618): at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
    E/MessageQueue-JNI( 5618): at android.
    D/AndroidRuntime( 5618): Shutting down VM
    E/AndroidRuntime( 5618): FATAL EXCEPTION: main
    E/AndroidRuntime( 5618): Process: com.ushahidi.android.internal, PID: 5618
    E/AndroidRuntime( 5618): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareTo(java.lang.String)' on a null object reference
    E/AndroidRuntime( 5618): at com.ushahidi.android.presentation.view.ui.adapter.PostAdapter.lambda$sortByTitle$63(PostAdapter.java:152)
    E/AndroidRuntime( 5618): at com.ushahidi.android.presentation.view.ui.adapter.PostAdapter.access$lambda$1(PostAdapter.java)
    E/AndroidRuntime( 5618): at com.ushahidi.android.presentation.view.ui.adapter.PostAdapter$$Lambda$2.compare(Unknown Source)
    E/AndroidRuntime( 5618): at java.util.TimSort.binarySort(TimSort.java:261)
    E/AndroidRuntime( 5618): at java.util.TimSort.sort(TimSort.java:204)
    E/AndroidRuntime( 5618): at java.util.TimSort.sort(TimSort.java:169)
    E/AndroidRuntime( 5618): at java.util.Arrays.sort(Arrays.java:2010)
    E/AndroidRuntime( 5618): at java.util.Collections.sort(Collections.java:1883)
    E/AndroidRuntime( 5618): at com.ushahidi.android.presentation.view.ui.adapter.PostAdapter.sortByTitle(PostAdapter.java:152)
    E/AndroidRuntime( 5618): at com.ushahidi.android.presentation.view.ui.fragment.ListPostFragment.sortByTitle(ListPostFragment.java:221)
    E/AndroidRuntime( 5618): at com.ushahidi.android.presentation.view.ui.fragment.ListPostFragment.onOptionsItemSelected(ListPostFragment.java:204)
    E/AndroidRuntime( 5618): at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2070)
    E/AndroidRuntime( 5618): at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2108)
    E/AndroidRuntime( 5618): at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:295)
    E/AndroidRuntime( 5618): at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:331)
    E/AndroidRuntime( 5618): at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
    E/AndroidRuntime( 5618): at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
    E/AndroidRuntime( 5618): at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
    E/AndroidRuntime( 5618): at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:73)
    E/AndroidRuntime( 5618): at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
    E/AndroidRuntime( 5618): at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
    E/AndroidRuntime( 5618): at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
    E/AndroidRuntime( 5618): at android.support.v7.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:84)
    E/AndroidRuntime( 5618): at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    E/AndroidRuntime( 5618): at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
    E/AndroidRuntime( 5618): at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
    E/AndroidRuntime( 5618): at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:191)
    E/AndroidRuntime( 5618): at android.widget.AdapterView.performItemClick(AdapterView.java:305)
    E/AndroidRuntime( 5618): at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
    E/AndroidRuntime( 5618): at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
    E/AndroidRuntime( 5618): at android.widget.AbsListView.onTouchUp(AbsListView.java:3872)
    E/AndroidRuntime( 5618): at android.widget.AbsListView.onTouchEvent(AbsListView.java:3637)
    E/AndroidRuntime( 5618): at android.view.View.dispatchTouchEvent(View.java:8471)
    E/AndroidRuntime( 5618): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
    E/AndroidRuntime( 5618): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
    E/AndroidRuntime( 5618): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
    E/AndroidRuntime( 5618): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
    E/AndroidRuntime( 5618): at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1731)
    E/AndroidRuntime( 5618): at android.view.View.dispatchPointerEvent(View.java:8666)
    E/AndroidRuntime( 5618): at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
    E/AndroidRuntime( 5618): at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
    E/AndroidRuntime( 5618): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
    E/AndroidRuntime( 5618): at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
    E/AndroidRuntime( 5618): at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
    E/AndroidRuntime( 5618): at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
    E/AndroidRuntime( 5618): at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
    E/AndroidRuntime( 5618): at android.view.V
    W/ActivityManager(  513):   Force finishing activity 1 com.ushahidi.android.internal/com.ushahidi.android.presentation.view.ui.activity.PostActivity```

**Comment by ymhuang0808** [comment]
I am unable to reproduce the bug. Can you give me a hint?
